### PR TITLE
Simplify package configuration

### PR DESCRIPTION
**Pull request by bndabbs**
This simplifies the multiple package tasks into a single task.

### CODE REVIEW

**Comment by dcode** [comment]
@bndabbs this patch leaves out `rocknsm_package_list` which is an array located in `files/rocknsm_config.dist.yml`. These packages are also needed. Can you adjust your patch to include all of these packages (they are all install state) and update to latest commit?

**Comment by dcode** [comment]
I updated this to the `devel` branch. Please update your changes to that branch and re-commit to your branch.

**Comment by dcode** [comment]
@bndabbs we'll be merging `devel` to `master` soon. If you can resolve this PR this week we'll include it.

**Comment by bndabbs** [comment]
Commit 576fa27 has been tested and should resolve the issue you raised @dcode.

**Pull request merged**
